CREATE TABLE PERSON (ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(200) NOT NULL, SURNAME VARCHAR(200) NOT NULL);
INSERT INTO PERSON(NAME, SURNAME) VALUES('Edson', 'Yanaga');
INSERT INTO PERSON(NAME, SURNAME) VALUES('Robert', 'Lewandowski');
INSERT INTO PERSON(NAME, SURNAME) VALUES('Arkadiusz', 'Milik');
